### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by pelson** [pyugrid/pyugrid#92]
Just tried building pyugrid on Python 3, and got the following error:

```
===== testing package: pyugrid-0.1.1-nppy34_1 =====
import: u'pyugrid'
Traceback (most recent call last):
  File "/home/travis/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import pyugrid
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/pyugrid/__init__.py", line 7, in <module>
    from .ugrid import UGrid
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/pyugrid/ugrid.py", line 23, in <module>
    from .util import point_in_tri
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/pyugrid/util.py", line 35
    return False
               ^
TabError: inconsistent use of tabs and spaces in indentation
TESTS FAILED: pyugrid-0.1.1-nppy34_1
```

Just wondering whether py3 support been looked at in pyugrid yet?

**Comment by ocefpaf** [comment]
I think I have a branch that fixes this.  Let me clean it up a little bit and I will send a PR in a few hours.

**Comment by QuLogic** [comment]
Why are you building 0.1.1 and not 0.1.6?
